import { registerTemplate } from '../core/registry';
import { bcTemplate } from './bc';
import { caTemplate } from './ca';
import { cnTemplate } from './cn';
import { crTemplate } from './cr';
import { euTemplate } from './eu';
import { iqTemplate } from './iq';
import { irTemplate } from './ir';
import { jpTemplate } from './jp';
import { krTemplate } from './kr';
import { mercosurTemplate } from './mercosur';
import { usTemplate } from './us';
import { vnTemplate } from './vn';

registerTemplate(usTemplate);
registerTemplate(euTemplate);
registerTemplate(cnTemplate);
registerTemplate(jpTemplate);
registerTemplate(bcTemplate);
registerTemplate(caTemplate);
registerTemplate(iqTemplate);
registerTemplate(irTemplate);
registerTemplate(krTemplate);
registerTemplate(vnTemplate);
registerTemplate(crTemplate);
registerTemplate(mercosurTemplate);
