/** Frozen requested-source records plus recovered prior specimens. */
export const IRAN_EVIDENCE_RECORDS = [
  {
    "id": "ir-wlp-1949-private",
    "label": "City initial / year-tab passenger",
    "presetId": "historical-1328",
    "status": "inspected photograph within collector sheet",
    "note": "Year tab 28 supports SH1328, 1949/50; earliest issue of this family not established. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_GI.jpg",
    "dateLabel": "1949 / SH1328",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Narrow left compartment city initial above dark rectangular year tab; four tall serial figures on right."
  },
  {
    "id": "ir-wlp-1963-private",
    "label": "City initial / year above initial",
    "presetId": "historical-1342",
    "status": "inspected photograph within collector sheet",
    "note": "SH1342 is 1963/64; date is on specimen, not proof of introduction. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_GI.jpg",
    "dateLabel": "1963 / SH1342",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Left ~16% has year above city initial, thin small separator; five figures including diamond zero at right."
  },
  {
    "id": "ir-wlp-1964-private",
    "label": "Full-city side-panel passenger",
    "presetId": "full-city-1964",
    "status": "inspected photograph within collector sheet",
    "note": "Small extension appears13 under enlarged pixel inspection, but recovered prior notes transcribed12. Small glyph remains uncertain; preserve image and do not silently propagate12. No endpoint established by requested source. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_GI.jpg",
    "dateLabel": "1964 series",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Full city at top left with extension below; left panel ~27%; four tall right-hand digits; no full-height divider."
  },
  {
    "id": "ir-wlp-1969-gilan",
    "label": "Rasht full-city two-line",
    "presetId": "full-city-gilan",
    "status": "inspected photograph within collector sheet",
    "note": "Series caption; photo date not given. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_GI.jpg",
    "dateLabel": "1969 series",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Five digits upper ~60%, centered sweeping connected city wordmark lower; compact."
  },
  {
    "id": "ir-wlp-1969-tehran",
    "label": "Tehran city/numeric-extension",
    "presetId": "full-city-numeric",
    "status": "inspected photograph within collector sheet",
    "note": "Do not silently resolve class conflict from tint; may be same image reused with different catalogue classification. WLP places in passenger sheet; recovered DNA attributes identical specimen to diplomatic category. Preserve conflict. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_GI.jpg",
    "dateLabel": "1969 series",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Five digits upper row; city plus numeric extension lower row."
  },
  {
    "id": "ir-wlp-1993-private",
    "label": "City-band passenger",
    "presetId": "city-band-header-code",
    "status": "inspected photograph within collector sheet",
    "note": "WLP attributes 1993; recovered collector dates include 1998. Keep earliest label as secondary, not statutory launch. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_GI.jpg",
    "dateLabel": "1993 series",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Orange-yellow header roughly 36% height; white lower serial 2+letter+3; black perimeter and horizontal divider."
  },
  {
    "id": "ir-wlp-2003-private",
    "label": "National passenger",
    "presetId": "national-private",
    "status": "inspected photograph within collector sheet",
    "note": "Catalogue attribution; contemporary report documents rollout Esfand1382 (Feb–Mar2004), operation April2004. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_GI.jpg",
    "dateLabel": "2003 series",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Long national plate: left blue stripe, Persian serial, right code box headed ایران."
  },
  {
    "id": "ir-wlp-1954-commercial",
    "label": "City initial / abbreviated-year commercial",
    "presetId": "historical-1333-commercial",
    "status": "inspected photograph within collector sheet",
    "note": "Specimen-year attribution; SH1333 is 1954/55. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_OT1.jpg",
    "dateLabel": "1954 / SH1333",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Long black panel; narrow city/year column at left; three serial digits incl two diamonds."
  },
  {
    "id": "ir-wlp-1960s-consular",
    "label": "Legacy consular",
    "presetId": "consular-1960s",
    "status": "inspected photograph within collector sheet",
    "note": "Decade only; no precise introduction/date visible. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_OT1.jpg",
    "dateLabel": "1960s",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Long shallow panel; connected consular legend left, one very large figure right."
  },
  {
    "id": "ir-wlp-circa1970-commercial",
    "label": "City/numeric-extension commercial",
    "presetId": "full-city-commercial",
    "status": "inspected photograph within collector sheet",
    "note": "Approximate collector date. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_OT1.jpg",
    "dateLabel": "circa 1970",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Five tall digits above city and 12 extension; no line separating rows."
  },
  {
    "id": "ir-wlp-teh-black",
    "label": "Additional foreign-travel plate TEH",
    "presetId": "international-teh",
    "status": "inspected photograph within collector sheet",
    "note": "Parallel supplementary foreign-travel plate; not domestic replacement. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_OT1.jpg",
    "dateLabel": "1969–1998",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Single Latin row, tall condensed block capitals, shallow long rectangle, rounded black rim."
  },
  {
    "id": "ir-wlp-teh-green",
    "label": "Additional foreign-travel plate TEH, green lettering",
    "presetId": "international-teh-green",
    "status": "inspected photograph within collector sheet",
    "note": "Same period label as black example; not independent redesign. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_OT1.jpg",
    "dateLabel": "1969–1998",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Single Latin row with green border; five serial digits."
  },
  {
    "id": "ir-wlp-1993-commercial",
    "label": "City-band commercial/public/temporary",
    "presetId": "city-band-commercial-wlp",
    "status": "inspected photograph within collector sheet",
    "note": "WLP groups multiple classes under same image; do not claim separate unseen layouts. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_OT2.jpg",
    "dateLabel": "1993 series",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Colored top city band, white lower row with 2+letter+3 serial."
  },
  {
    "id": "ir-wlp-1993-government",
    "label": "City-band government",
    "presetId": "city-band-government",
    "status": "inspected photograph within collector sheet",
    "note": "Series attribution only; exact fleet rollout not established. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_OT2.jpg",
    "dateLabel": "1993 series",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Blue city header over white 2+letter+3 serial."
  },
  {
    "id": "ir-wlp-thr-travel",
    "label": "Additional foreign-travel plate THR",
    "presetId": "international-thr",
    "status": "inspected photograph within collector sheet",
    "note": "Parallel supplementary foreign-travel plate. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_OT2.jpg",
    "dateLabel": "1998–2005",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Single condensed Latin row across long yellow plate."
  },
  {
    "id": "ir-wlp-aa-public-2002",
    "label": "Short-lived bilingual public transport",
    "presetId": "public-2002",
    "status": "inspected photograph within collector sheet",
    "note": "WLP class label public transport, not generic foreign travel. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_OT2.jpg",
    "dateLabel": "2002–2003",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Compact ~2.55 ratio in source; narrow left blue stripe. Top yellow/orange row has Persian code111+five digits, bottom white row AA+Latin five digits; vertical separator between code and digits, horizontal center rule."
  },
  {
    "id": "ir-wlp-2003-public",
    "label": "National public transport",
    "presetId": "national-public",
    "status": "inspected photograph within collector sheet",
    "note": "National-family date dispute documented separately. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_OT2.jpg",
    "dateLabel": "2003 series",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "National long with right code box and left stripe."
  },
  {
    "id": "ir-wlp-travel-circa2010",
    "label": "Touring and Automobile Club foreign-travel",
    "presetId": "international-2010",
    "status": "inspected photograph within collector sheet",
    "note": "Approximate collector date; no exact introduction day verified. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_OT2.jpg",
    "dateLabel": "circa 2010",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Blue exterior/frame/footer; narrow blue badge left; white main field with Latin digits; E white on red insert; right blue two-digit box."
  },
  {
    "id": "ir-wlp-fake-police",
    "label": "Excluded fake police-looking specimen",
    "presetId": null,
    "status": "excluded fake",
    "note": "Do not offer as authentic template or trace source. WLP sheet labels this image Fake! Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_OT2.jpg",
    "dateLabel": "undated",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "National-looking green composition. Retain only as exclusion/evidence row."
  },
  {
    "id": "ir-wlp-qeshm-circa2010",
    "label": "Qeshm local free-zone",
    "presetId": "free-zone-old-qeshm",
    "status": "inspected photograph within collector sheet",
    "note": "Approximate collector date of local generation; distinct from 2017 national free-zone redesign. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_FZQ.jpg",
    "dateLabel": "circa 2010",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Compact; white left logo/name column ~25%; right 5 Persian digits top and repeated Latin digits below; horizontal center rule and left vertical rule."
  },
  {
    "id": "ir-wlp-us-military",
    "label": "US forces",
    "presetId": "us-military",
    "status": "inspected photograph within collector sheet",
    "note": "Collector period range; not 1979 domestic redesign. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/FO_IRAN_USAX.jpg",
    "dateLabel": "1950s–1979",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Wide shallow panel, orange border field around central white serial inset; three black Persian digits."
  },
  {
    "id": "ir-wlp-us-topographical",
    "label": "US Topographical Training Team",
    "presetId": "us-topographical",
    "status": "inspected photograph within collector sheet",
    "note": "Collector period range only. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/FO_IRAN_USAX.jpg",
    "dateLabel": "1963–1971",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Persian legend at left; five figures right; black rim."
  },
  {
    "id": "ir-wlp-uniimog",
    "label": "UN Iran–Iraq Military Observer Group",
    "presetId": "un-observer",
    "status": "inspected photograph within collector sheet",
    "note": "Mission period, not individual photograph date. Sheet revision, if listed, is not specimen photograph or introduction date.",
    "sourceUrl": "http://www.worldlicenseplates.com/world/AS_IRAN.html",
    "imageUrl": "http://www.worldlicenseplates.com/jpglps/AS_IRAN_UN.jpg",
    "dateLabel": "1988–1991",
    "scope": "requested-source",
    "rights": "WorldLicensePlates and original contributors; permission not established. Private research reference; do not publish photos as freely licensed assets.",
    "geometry": "Compact near1.6:1; large serif Latin UNIIMOG top, two figures centered below."
  },
  {
    "id": "ir-wiki-private",
    "label": "Iran private",
    "presetId": "national-private",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Do not date every subclass to national system rollout.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/Iran_private_vehicle_number_plate.svg/500px-Iran_private_vehicle_number_plate.svg.png",
    "dateLabel": "national era; subclass launch unverified",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures."
  },
  {
    "id": "ir-wiki-accessible",
    "label": "Iran accessible",
    "presetId": "national-accessible",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Do not date every subclass to national system rollout.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Iran_disabled_vehicle_number_plate.svg/500px-Iran_disabled_vehicle_number_plate.svg.png",
    "dateLabel": "national era; subclass launch unverified",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures."
  },
  {
    "id": "ir-wiki-taxi",
    "label": "Iran taxi",
    "presetId": "national-taxi",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Do not date every subclass to national system rollout.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Iran_taxi_number_plate.svg/500px-Iran_taxi_number_plate.svg.png",
    "dateLabel": "national era; subclass launch unverified",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures."
  },
  {
    "id": "ir-wiki-public",
    "label": "Iran public",
    "presetId": "national-public",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Do not date every subclass to national system rollout.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d2/Iran_public_vehicles_number_plate.svg/500px-Iran_public_vehicles_number_plate.svg.png",
    "dateLabel": "national era; subclass launch unverified",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures."
  },
  {
    "id": "ir-wiki-agricultural",
    "label": "Iran agricultural",
    "presetId": "national-agricultural",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Do not date every subclass to national system rollout.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Iran_agricultural_vehicle_number_plate.svg/500px-Iran_agricultural_vehicle_number_plate.svg.png",
    "dateLabel": "national era; subclass launch unverified",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures."
  },
  {
    "id": "ir-wiki-government",
    "label": "Iran government",
    "presetId": "national-government",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Do not date every subclass to national system rollout.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Iran_government_vehicle_number_plate.svg/500px-Iran_government_vehicle_number_plate.svg.png",
    "dateLabel": "national era; subclass launch unverified",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures."
  },
  {
    "id": "ir-wiki-protocol",
    "label": "Iran protocol",
    "presetId": "protocol",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Do not date every subclass to national system rollout.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Pelak_melie_tashrifat.png/500px-Pelak_melie_tashrifat.png",
    "dateLabel": "national era; subclass launch unverified",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "Long; blueleft ~10%, joined تشریفات above Latin PROTOCOL in left-center, four Persian serial figures on right; no right region box."
  },
  {
    "id": "ir-wiki-police",
    "label": "Iran police",
    "presetId": "national-police",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Wikipedia date not linked to primary announcement; applies to this modern police format.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/04/Pelak_melie_polis.png/500px-Pelak_melie_polis.png",
    "dateLabel": "2012-09-30",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures."
  },
  {
    "id": "ir-wiki-irgc",
    "label": "Iran irgc",
    "presetId": "national-irgc",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Wikipedia claims replacement planned by March2017; completion not verified.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Pelak_melie_sepah.png/500px-Pelak_melie_sepah.png",
    "dateLabel": "2016-05-30",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures."
  },
  {
    "id": "ir-wiki-army",
    "label": "Iran army",
    "presetId": "national-army",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Wikipedia claims replacement planned by March2017; completion not verified.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Pelak_melie_artesh.png/500px-Pelak_melie_artesh.png",
    "dateLabel": "2016-05-30",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures."
  },
  {
    "id": "ir-wiki-defence",
    "label": "Iran defence",
    "presetId": "national-defence",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Wikipedia claims replacement planned by March2017; completion not verified.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/Pelak_melie_vezarat_defa%27.png/500px-Pelak_melie_vezarat_defa%27.png",
    "dateLabel": "2016-05-30",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures."
  },
  {
    "id": "ir-wiki-staff",
    "label": "Iran staff",
    "presetId": "national-staff",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Wikipedia claims replacement planned by March2017; completion not verified.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Pelak_melie_setad_kol.png/500px-Pelak_melie_setad_kol.png",
    "dateLabel": "2016-05-30",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures."
  },
  {
    "id": "ir-wiki-historic",
    "label": "Iran historic",
    "presetId": "historic-vehicle",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "This is a modern class for old cars, not historical-era registration.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Pelak_melie_tarikhi.png/250px-Pelak_melie_tarikhi.png",
    "dateLabel": "modern historical-vehicle class; introduction unknown",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "Compact2:1; blue left35% includes flag at top and Bagh-e Melli picture at foot; brown right split horizontally, historical word above five-digit serial."
  },
  {
    "id": "ir-wiki-diplomatic",
    "label": "Iran diplomatic",
    "presetId": "national-diplomatic",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Unveiling is not fleet replacement completion.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Pelak_melie_siasi.png/500px-Pelak_melie_siasi.png",
    "dateLabel": "2016-03-06 unveiling; 2016-04/05 planned operation",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures. Right-box heading is class word, not ایران."
  },
  {
    "id": "ir-wiki-service",
    "label": "Iran service",
    "presetId": "national-service",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Unveiling is not fleet replacement completion.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/83/Pelak_melie_service.png/500px-Pelak_melie_service.png",
    "dateLabel": "2016-03-06 unveiling; 2016-04/05 planned operation",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures. Right-box heading is class word, not ایران."
  },
  {
    "id": "ir-wiki-diplomatic-previous",
    "label": "Iran diplomatic previous",
    "presetId": "diplomatic-old",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "No precise start or all-vehicle withdrawal date in article.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Pelak_siasi.png/250px-Pelak_siasi.png",
    "dateLabel": "before2016 replacement; start unknown",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "Compact2:1; large three-digit serial uppercenter, smaller two-digit code at lowerleft; connected class word lowerright; no stripe or internal border."
  },
  {
    "id": "ir-wiki-service-previous",
    "label": "Iran service previous",
    "presetId": "service-old",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "No precise start or all-vehicle withdrawal date in article.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b3/Pelak_servis.png/250px-Pelak_servis.png",
    "dateLabel": "before2016 replacement; start unknown",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "Compact2:1; large three-digit serial uppercenter, smaller two-digit code at lowerleft; connected class word lowerright; no stripe or internal border."
  },
  {
    "id": "ir-wiki-temporary",
    "label": "Iran temporary",
    "presetId": "temporary",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Do not date every subclass to national system rollout.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/%D9%BE%D9%84%D8%A7%DA%A9_%D9%85%D9%88%D9%82%D8%AA.jpg/500px-%D9%BE%D9%84%D8%A7%DA%A9_%D9%85%D9%88%D9%82%D8%AA.jpg",
    "dateLabel": "national era; subclass launch unverified",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "National long: left blue band (~9% width), serial 2+class+3, right box (~21% width) with title above two figures. Right code panel split horizontally: ایران and small11 above; expiry96/4 below. Preserve expiry as distinct field."
  },
  {
    "id": "ir-wiki-temporary-previous",
    "label": "Iran temporary previous",
    "presetId": "temporary-old",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Source drawing has unresolved issue dates. Compact2:1; narrowleft26% split in two by horizontal line (5 above92); larger right panel has گذر موقت header and four-digit serial underneath.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c6/Pelak_gozar_movaqat.png/250px-Pelak_gozar_movaqat.png",
    "dateLabel": "previous temporary generation, exact period unknown",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "Compact2:1; narrowleft26% split in two by horizontal line (5 above92); larger right panel has گذر موقت header and four-digit serial underneath."
  },
  {
    "id": "ir-wiki-motorcycle",
    "label": "Iran motorcycle",
    "presetId": "motorcycle",
    "status": "inspected article-linked illustrative diagram (not presumed official specimen)",
    "note": "Do not date every subclass to national system rollout.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a1/Pelak_melie_motor.png/250px-Pelak_melie_motor.png",
    "dateLabel": "national era; subclass launch unverified",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked. Use original reconstruction, retain source link.",
    "geometry": "Compact~1.67:1; three-digit province code centered top, five-digit serial bottom; blueflag strip occupies upper left only. No horizontal divider."
  },
  {
    "id": "ir-wiki-freezone-anzali",
    "label": "Anzali local free-zone design",
    "presetId": "free-zone-old-anzali",
    "status": "inspected article-linked illustrative diagram",
    "note": "Sample serial12365; diagram is an illustration, not an introduction-dated specimen. Wikipedia gives no start date; do not treat logo or file upload date as issue date.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d5/Pelake_MAT_Anzali.png/250px-Pelake_MAT_Anzali.png",
    "dateLabel": "local generation, before2017 common redesign",
    "scope": "requested-source",
    "rights": "Wikimedia individual file license not verified; source link retained",
    "geometry": "Compact~2:1; blue leftcolumn35% with flag, zone emblem, Latin zone name; white right area divided horizontally with Persian five digits above same Latin digits below."
  },
  {
    "id": "ir-wiki-freezone-aras",
    "label": "Aras local free-zone design",
    "presetId": "free-zone-old-aras",
    "status": "inspected article-linked illustrative diagram",
    "note": "Sample serial12365; diagram is an illustration, not an introduction-dated specimen. Wikipedia gives no start date; do not treat logo or file upload date as issue date.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Pelake_MAT_Aras.png/250px-Pelake_MAT_Aras.png",
    "dateLabel": "local generation, before2017 common redesign",
    "scope": "requested-source",
    "rights": "Wikimedia individual file license not verified; source link retained",
    "geometry": "Compact~2:1; blue leftcolumn35% with flag, zone emblem, Latin zone name; white right area divided horizontally with Persian five digits above same Latin digits below."
  },
  {
    "id": "ir-wiki-freezone-arvand",
    "label": "Arvand local free-zone design",
    "presetId": "free-zone-old-arvand",
    "status": "inspected article-linked illustrative diagram",
    "note": "Sample serial12365; diagram is an illustration, not an introduction-dated specimen. Wikipedia gives no start date; do not treat logo or file upload date as issue date.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Pelake_MAT_Arvand.png/250px-Pelake_MAT_Arvand.png",
    "dateLabel": "local generation, before2017 common redesign",
    "scope": "requested-source",
    "rights": "Wikimedia individual file license not verified; source link retained",
    "geometry": "Compact~2:1; blue leftcolumn35% with flag, zone emblem, Latin zone name; white right area divided horizontally with Persian five digits above same Latin digits below."
  },
  {
    "id": "ir-wiki-freezone-kish",
    "label": "Kish local free-zone design",
    "presetId": "free-zone-old-kish",
    "status": "inspected article-linked illustrative diagram",
    "note": "Sample serial12365; diagram is an illustration, not an introduction-dated specimen. Wikipedia gives no start date; do not treat logo or file upload date as issue date.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/Pelake_MAT_Kish.png/250px-Pelake_MAT_Kish.png",
    "dateLabel": "local generation, before2017 common redesign",
    "scope": "requested-source",
    "rights": "Wikimedia individual file license not verified; source link retained",
    "geometry": "Compact~2:1; blue leftcolumn35% with flag, zone emblem, Latin zone name; white right area divided horizontally with Persian five digits above same Latin digits below."
  },
  {
    "id": "ir-wiki-freezone-maku",
    "label": "Maku local free-zone design",
    "presetId": "free-zone-old-maku",
    "status": "inspected article-linked illustrative diagram",
    "note": "Sample11111; drawn emblem is yellow-orange oval with curved blue-and-white ribbon. Wikipedia gives no start date; do not treat logo or file upload date as issue date.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Pelake_MAT_MAKU.png/250px-Pelake_MAT_MAKU.png",
    "dateLabel": "local generation, before2017 common redesign",
    "scope": "requested-source",
    "rights": "Wikimedia individual file license not verified; source link retained",
    "geometry": "Compact~2:1; blue leftcolumn35% with flag, zone emblem, Latin zone name; white right area divided horizontally with Persian five digits above same Latin digits below."
  },
  {
    "id": "ir-wiki-freezone-chabahar",
    "label": "Chabahar local free-zone design",
    "presetId": "free-zone-old-chabahar",
    "status": "inspected article-linked illustrative diagram",
    "note": "Diagram shows12365 Persian but12356 Latin. Preserve discrepancy in evidence; editor should keep repeated number consistent by default. Wikipedia gives no start date; do not treat logo or file upload date as issue date.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2c/Pelake_MAT_Chabahar.png/250px-Pelake_MAT_Chabahar.png",
    "dateLabel": "local generation, before2017 common redesign",
    "scope": "requested-source",
    "rights": "Wikimedia individual file license not verified; source link retained",
    "geometry": "Compact~2:1; narrowblueleft25% split horizontally: line-art emblemabove, چابهار below. Rightupperwhite Persianrow; rightlowerblue Latinrow in white."
  },
  {
    "id": "ir-wiki-freezone-qeshm",
    "label": "Qeshm local free-zone design",
    "presetId": "free-zone-old-qeshm",
    "status": "inspected article-linked illustrative diagram",
    "note": "Diagram shows12365 Persian but12356 Latin. Treat mismatch as source-artwork error, not a rule; WLP actual photo12713 matches both rows. Wikipedia gives no start date; do not treat logo or file upload date as issue date.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Pelake_MAT_Qeshm.png/250px-Pelake_MAT_Qeshm.png",
    "dateLabel": "local generation, before2017 common redesign",
    "scope": "requested-source",
    "rights": "Wikimedia individual file license not verified; source link retained",
    "geometry": "Compact~2:1; white leftcolumn25% with circular orange/blue wave emblem and قشم wordmark; right splitrows Persianabove/Latinbelow."
  },
  {
    "id": "ir-freezone-2017-private",
    "label": "2017 unified free-zone private",
    "presetId": null,
    "status": "text-only · geometry barrier",
    "note": "Text verifies Qeshm pilot on 1 August 2017, 360 × 150 mm, bilingual numbers, zone emblem and white/yellow/red class colours. The only report image is a generic news placeholder: no geometry or zone-code arrangement can be reconstructed.",
    "sourceUrl": "https://www.sarpoosh.com/car-news/automobile/automobile960502629.html",
    "imageUrl": null,
    "dateLabel": "2017-08-01",
    "scope": "supporting-text",
    "rights": "",
    "geometry": "Bilingual numbers and zone emblem reported; exact visual arrangement not authenticated in this pass."
  },
  {
    "id": "ir-freezone-2017-public",
    "label": "2017 unified free-zone public",
    "presetId": null,
    "status": "text-only · geometry barrier",
    "note": "Text verifies Qeshm pilot on 1 August 2017, 360 × 150 mm, bilingual numbers, zone emblem and white/yellow/red class colours. The only report image is a generic news placeholder: no geometry or zone-code arrangement can be reconstructed.",
    "sourceUrl": "https://www.sarpoosh.com/car-news/automobile/automobile960502629.html",
    "imageUrl": null,
    "dateLabel": "2017-08-01",
    "scope": "supporting-text",
    "rights": "",
    "geometry": "Bilingual numbers and zone emblem reported; exact visual arrangement not authenticated in this pass."
  },
  {
    "id": "ir-freezone-2017-government",
    "label": "2017 unified free-zone government",
    "presetId": null,
    "status": "text-only · geometry barrier",
    "note": "Text verifies Qeshm pilot on 1 August 2017, 360 × 150 mm, bilingual numbers, zone emblem and white/yellow/red class colours. The only report image is a generic news placeholder: no geometry or zone-code arrangement can be reconstructed.",
    "sourceUrl": "https://www.sarpoosh.com/car-news/automobile/automobile960502629.html",
    "imageUrl": null,
    "dateLabel": "2017-08-01",
    "scope": "supporting-text",
    "rights": "",
    "geometry": "Bilingual numbers and zone emblem reported; exact visual arrangement not authenticated in this pass."
  },
  {
    "id": "ir-wiki-photo-shiraz",
    "label": "Photographed national private plate, Shiraz",
    "presetId": "national-private",
    "status": "inspected actual vehicle photograph",
    "note": "Car model year in filename does not establish plate introduction or photograph date.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Iranian_plate.jpg",
    "dateLabel": "undated photograph",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked; source link retained.",
    "geometry": "National long family; left blue stripe and right codebox. Shiraz close-up is angled; Tehran full-vehicle image leaves very small plate. Do not trace exact die from the tiny Tehran photo."
  },
  {
    "id": "ir-wiki-photo-tehran",
    "label": "Photographed national private plate, Tehran",
    "presetId": "national-private",
    "status": "inspected actual vehicle photograph",
    "note": "Car model year in filename does not establish plate introduction or photograph date.",
    "sourceUrl": "https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Iran",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/2007_Mercedes-Benz_W209_CLK_350_Cabriolet_in_Iran.jpg/250px-2007_Mercedes-Benz_W209_CLK_350_Cabriolet_in_Iran.jpg",
    "dateLabel": "undated photograph",
    "scope": "requested-source",
    "rights": "Wikimedia file-specific license not independently checked; source link retained.",
    "geometry": "National long family; left blue stripe and right codebox. Shiraz close-up is angled; Tehran full-vehicle image leaves very small plate. Do not trace exact die from the tiny Tehran photo."
  },
  {
    "id": "iran47trucku",
    "label": "1947 / SH 1326 truck",
    "presetId": "historical-1326",
    "status": "inspected prior photograph",
    "note": "White on black, single four-digit row; left city initial over separator and year Physical layout observed; dates and class dependent on collector metadata",
    "sourceUrl": "https://dna.nl/iran.htm",
    "imageUrl": "https://dna.nl/mideast/iran47trucku.jpg",
    "dateLabel": "1947–48 specimen date; issue boundary unverified",
    "scope": "prior-inspected",
    "rights": "Unspecified; research reference, do not redistribute as licensed source",
    "geometry": "White on black, single four-digit row; left city initial over separator and year"
  },
  {
    "id": "iran56caru",
    "label": "1956 / SH 1335 passenger",
    "presetId": "historical-1335",
    "status": "inspected prior photograph",
    "note": "Black on cream/white; left city initial above contrasting year tab Physical layout observed; dates and class dependent on collector metadata",
    "sourceUrl": "https://dna.nl/iran.htm",
    "imageUrl": "https://dna.nl/mideast/iran56caru.jpg",
    "dateLabel": "1956–57 specimen date; issue boundary unverified",
    "scope": "prior-inspected",
    "rights": "Unspecified; research reference, do not redistribute as licensed source",
    "geometry": "Black on cream/white; left city initial above contrasting year tab"
  },
  {
    "id": "iran60caru",
    "label": "1960 / SH 1339 passenger",
    "presetId": "historical-1339",
    "status": "inspected prior photograph",
    "note": "Black on white; left city initial above contrasting year tab Physical layout observed; dates and class dependent on collector metadata",
    "sourceUrl": "https://dna.nl/iran.htm",
    "imageUrl": "https://dna.nl/mideast/iran60caru.jpg",
    "dateLabel": "1960–61 specimen date; issue boundary unverified",
    "scope": "prior-inspected",
    "rights": "Unspecified; research reference, do not redistribute as licensed source",
    "geometry": "Black on white; left city initial above contrasting year tab"
  },
  {
    "id": "iran61caru",
    "label": "1961 / SH 1340 passenger",
    "presetId": "historical-1340",
    "status": "inspected prior photograph",
    "note": "Black on white; five digits, thin rim and separate light year tab Physical layout observed; dates and class dependent on collector metadata",
    "sourceUrl": "https://dna.nl/iran.htm",
    "imageUrl": "https://dna.nl/mideast/iran61caru.jpg",
    "dateLabel": "1961–62 specimen date; issue boundary unverified",
    "scope": "prior-inspected",
    "rights": "Unspecified; research reference, do not redistribute as licensed source",
    "geometry": "Black on white; five digits, thin rim and separate light year tab"
  },
  {
    "id": "iran63caru",
    "label": "1963 / SH 1342 passenger",
    "presetId": "historical-1342",
    "status": "inspected prior photograph",
    "note": "Black on pale plate; five digits including diamond-like zero Physical layout observed; dates and class dependent on collector metadata",
    "sourceUrl": "https://dna.nl/iran.htm",
    "imageUrl": "https://dna.nl/mideast/iran63caru.jpg",
    "dateLabel": "1963–64 specimen date; issue boundary unverified",
    "scope": "prior-inspected",
    "rights": "Unspecified; research reference, do not redistribute as licensed source",
    "geometry": "Black on pale plate; five digits including diamond-like zero"
  },
  {
    "id": "iran70acaru",
    "label": "Full-city four-digit family",
    "presetId": "full-city-1964",
    "status": "inspected prior photograph",
    "note": "Black on pale plate; full city legend at upper left, extension below; four tall digits Physical layout observed; dates and class dependent on collector metadata",
    "sourceUrl": "https://dna.nl/iran.htm",
    "imageUrl": "https://dna.nl/mideast/iran70acaru.jpg",
    "dateLabel": "Archive says 1964–1972?; exact endpoint unresolved",
    "scope": "prior-inspected",
    "rights": "Unspecified; research reference, do not redistribute as licensed source",
    "geometry": "Black on pale plate; full city legend at upper left, extension below; four tall digits"
  },
  {
    "id": "iran70bcaru",
    "label": "Full-city five-digit family",
    "presetId": "full-city-letter",
    "status": "inspected prior photograph",
    "note": "Black on pale plate; five figures above city/letter extension Physical layout observed; dates and class dependent on collector metadata",
    "sourceUrl": "https://dna.nl/iran.htm",
    "imageUrl": "https://dna.nl/mideast/iran70bcaru.jpg",
    "dateLabel": "Archive says 1972?–1993?; UNIDO confirms general passenger replate 1969/70",
    "scope": "prior-inspected",
    "rights": "Unspecified; research reference, do not redistribute as licensed source",
    "geometry": "Black on pale plate; five figures above city/letter extension"
  },
  {
    "id": "iran70caru",
    "label": "Earlier diplomatic family",
    "presetId": "full-city-numeric",
    "status": "inspected prior photograph",
    "note": "Black on pale pink plate; five figures above city/code; archive says 91 Venezuela but independently unverified Physical layout observed; dates and class dependent on collector metadata",
    "sourceUrl": "https://dna.nl/iran.htm",
    "imageUrl": "https://dna.nl/mideast/iran70caru.jpg",
    "dateLabel": "Undated archive specimen",
    "scope": "prior-inspected",
    "rights": "Unspecified; research reference, do not redistribute as licensed source",
    "geometry": "Black on pale pink plate; five figures above city/code; archive says 91 Venezuela but independently unverified"
  },
  {
    "id": "iran72govtu",
    "label": "Older government family",
    "presetId": "old-government",
    "status": "inspected prior photograph",
    "note": "Five figures only on pale cream image; official class attribution relies on archive Physical layout observed; dates and class dependent on collector metadata",
    "sourceUrl": "https://dna.nl/iran.htm",
    "imageUrl": "https://dna.nl/mideast/iran72govtu.jpg",
    "dateLabel": "Undated archive specimen",
    "scope": "prior-inspected",
    "rights": "Unspecified; research reference, do not redistribute as licensed source",
    "geometry": "Five figures only on pale cream image; official class attribution relies on archive"
  },
  {
    "id": "iran98trucku",
    "label": "City-band commercial family",
    "presetId": "city-band-commercial",
    "status": "inspected prior photograph",
    "note": "Orange/yellow city band above white serial panel; compact, 320×155mm reported by DNA, not independently measured Physical layout observed; dates and class dependent on collector metadata",
    "sourceUrl": "https://dna.nl/iran.htm",
    "imageUrl": "https://dna.nl/mideast/iran98trucku.jpg",
    "dateLabel": "1993–2003 per Olav; DNA labels 1998 onward, not harmonized",
    "scope": "prior-inspected",
    "rights": "Unspecified; research reference, do not redistribute as licensed source",
    "geometry": "Orange/yellow city band above white serial panel; compact, 320×155mm reported by DNA, not independently measured"
  },
  {
    "id": "iran05trucku",
    "label": "National public-transport family",
    "presetId": "national-public",
    "status": "inspected prior photograph",
    "note": "Black on yellow, blue left band, right boxed code Physical layout observed; dates and class dependent on collector metadata",
    "sourceUrl": "https://dna.nl/iran.htm",
    "imageUrl": "https://dna.nl/mideast/iran05trucku.jpg",
    "dateLabel": "National system 2003, confirmed by 2004 reporting; specimen labeled 2005?",
    "scope": "prior-inspected",
    "rights": "Unspecified; research reference, do not redistribute as licensed source",
    "geometry": "Black on yellow, blue left band, right boxed code"
  }
];
