"""Write src/templates/dies/traced-1940.ts from traced.json (+ sample counts)."""
import json, sys
t = json.load(open('out/traced.json'))
S = json.load(open('out/summary.json'))['summary']
def n(kind, era, c): return S.get(kind, {}).get(era, {}).get(c, {}).get('n', 0)
counts = {
  'serial': {c: n('serial', '1940-48', c) + n('serial', '1949-51', c) for c in t['serial']},
  'serialLetters': {c: n('serial', 'all', c) for c in t['serialLetters']},
  'legend': {c: n('legend', 'all', c) for c in t['legend']},
  'year': {c: n('year', 'all', c) for c in t['year']},
  'year52': {c: n('year52', 'all', c) for c in t['year52']},
  'strip': json.load(open('out/strip-counts.json')), 'tab': json.load(open('out/tab-counts.json')),
}
sets = [
  ('BC_SERIAL_1940', 'Serial dies, 1940–54: digits from 1940–51 plates, A/B/F from 1940–54.', {**t['serial'], **t['serialLetters']}, {**counts['serial'], **counts['serialLetters']}),
  ('BC_LEGEND_1940', 'BRITISH COLUMBIA legend dies, 1940–54.', t['legend'], counts['legend']),
  ('BC_YEAR_1940', 'Stacked-year digits at the right of 1940–51 bases.', t['year'], counts['year']),
  ('BC_YEAR_1952', 'The 52 on the 1952 base.', t['year52'], counts['year52']),
  ('BC_STRIP_1951', '1951 renewal strip legend (two high-resolution strips; smoothed more heavily).', t['strip'], counts['strip']),
  ('BC_TAB_1953', '1953/54 renewal-tab year digits.', t['tab'], counts['tab']),
]
# 1915–17 lithographed tin, one set per maker (tin.py).
tin = json.load(open('out/traced-tin.json')); tc = json.load(open('out/tin-counts.json'))
sets += [
  ('BC_TIN_MACDONALD', '1915 and 1916 (to No. 9,000) numerals, MacDonald Manufacturing.', tin['macdonald'], tc['serial-macdonald']),
  ('BC_TIN_TACEY', '1916 over-run and 1917 numerals, J.R. Tacey & Sons.', tin['tacey'], tc['serial-tacey']),
]
out = ['''/**
 * GENERATED by scripts/trace-bc-dies (do not edit by hand). Filled outlines in die units
 * (cap height 100, baseline y = 100), each traced from the average of every labelled sample of
 * that character found in BCpl8s passenger photographs. A photo's text comes from its file name
 * (serial) or from what the plate must say (year, legend); a photo is used only when the number
 * of shapes found matches that text. The photographs are references only and are not bundled.
 */
import type { SkeletonGlyph } from './skeleton';
''']
for name, doc, glyphs, cnt in sets:
    out.append(f'/** {doc} */\nexport const {name}: Readonly<Record<string, SkeletonGlyph>> = {{')
    for c, v in glyphs.items():
        out.append(f"  // {cnt.get(c, 0)} samples\n  {json.dumps(c)}: {{ advance: {v['advance']}, fill: true, paths: [{json.dumps(v['d'])}] }},")
    out.append('};\n')
open(sys.argv[1], 'w').write('\n'.join(out))
