"""Write src/templates/dies/traced-1940.ts from traced.json (+ sample counts)."""
import json, sys
t = json.load(open('out/traced.json'))
S = json.load(open('out/summary.json'))['summary']
def n(kind, era, c): return S.get(kind, {}).get(era, {}).get(c, {}).get('n', 0)
counts = {
  'serial': {c: n('serial', '1940-48', c) + n('serial', '1949-51', c) for c in t['serial']},
  'serialLetters': {c: n('serial', 'all', c) for c in t['serialLetters']},
  'legend': {c: n('legend', 'all', c) for c in t['legend']},
  'year': {c: n('year', 'all', c) for c in t['year']},
  'year52': {c: n('year52', 'all', c) for c in t['year52']},
  'strip': json.load(open('out/strip-counts.json')), 'tab': json.load(open('out/tab-counts.json')),
}
sets = [
  ('BC_SERIAL_1940', 'Serial dies, 1940–54: digits from 1940–51 plates, A/B/F from 1940–54.', {**t['serial'], **t['serialLetters']}, {**counts['serial'], **counts['serialLetters']}),
  ('BC_LEGEND_1940', 'BRITISH COLUMBIA legend dies, 1940–54.', t['legend'], counts['legend']),
  ('BC_YEAR_1940', 'Stacked-year digits at the right of 1940–51 bases.', t['year'], counts['year']),
  ('BC_YEAR_1952', 'The 52 on the 1952 base.', t['year52'], counts['year52']),
  ('BC_STRIP_1951', '1951 renewal strip legend (two high-resolution strips; smoothed more heavily).', t['strip'], counts['strip']),
  ('BC_TAB_1953', '1953/54 renewal-tab year digits.', t['tab'], counts['tab']),
]
# 1915–17 lithographed tin, one set per maker (tin.py).
tin = json.load(open('out/traced-tin.json')); tc = json.load(open('out/tin-counts.json'))
sets += [
  ('BC_TIN_MACDONALD', '1915 and 1916 (to No. 9,000) numerals, MacDonald Manufacturing.', tin['macdonald'], tc['serial-macdonald']),
  ('BC_TIN_TACEY', '1916 over-run and 1917 numerals, J.R. Tacey & Sons.', tin['tacey'], tc['serial-tacey']),
]
# 1924–39 date stamps: each year's two date digits are their own small dies (dates.py).
td = json.load(open('out/traced-dates.json')); dc = json.load(open('out/date-counts.json'))
date_sets = [(y[4:], g) for y, g in sorted(td.items())]
# 1930, Thompson Heating & Ventilating's one-year dies (series.py series/1930.json). No 8 was photographed.
t30 = json.load(open('out/traced-1930.json')); c30 = json.load(open('out/thompson-1930-counts.json'))
def mirror_x(d, width):
    # Paths from vectorize.py hold only M/L/C/Z with absolute "x y" pairs, so flipping is x -> width - x.
    out, nums = [], d.replace('M', ' M ').replace('L', ' L ').replace('C', ' C ').replace('Z', ' Z ').split()
    pair = []
    for tok in nums:
        if tok in 'MLCZ': out.append(tok); continue
        pair.append(float(tok))
        if len(pair) == 2: out.append(f'{width - pair[0]:.1f} {pair[1]:.1f}'); pair = []
    return ' '.join(out).replace('M ', 'M').replace('L ', 'L').replace('C ', 'C')
# No 1930 photo shows an 8: build one from the traced 3 and its mirror image (same strokes and bowls), flagged.
if '8' not in t30['serial'] and '3' in t30['serial']:
    three = t30['serial']['3']
    t30['serial']['8'] = {'advance': three['advance'], 'd': three['d'] + ' @@ ' + mirror_x(three['d'], three['advance'])}
    c30['serial']['8'] = 'synthesised from the 3 and its mirror image; 0'
sets += [
  ('BC_THOMPSON_1930', '1930 serial numerals (Thompson Heating & Ventilating); no 8 is known from photographs.', t30['serial'], c30['serial']),
  ('BC_LEGEND_1930', '1930 BRITISH COLUMBIA legend (Thompson).', t30['legend'], c30['legend']),
]
out = ['''/**
 * GENERATED by scripts/trace-bc-dies (do not edit by hand). Filled outlines in die units
 * (cap height 100, baseline y = 100), each traced from the average of every labelled sample of
 * that character found in BCpl8s passenger photographs. A photo's text comes from its file name
 * (serial) or from what the plate must say (year, legend); a photo is used only when the number
 * of shapes found matches that text. The photographs are references only and are not bundled.
 */
import type { SkeletonGlyph } from './skeleton';
''']
for name, doc, glyphs, cnt in sets:
    out.append(f'/** {doc} */\nexport const {name}: Readonly<Record<string, SkeletonGlyph>> = {{')
    for c, v in glyphs.items():
        paths = v['d'].split(' @@ ') if ' @@ ' in v['d'] else [v['d']]
        out.append(f"  // {cnt.get(c, 0)} samples\n  {json.dumps(c)}: {{ advance: {v['advance']}, fill: true, paths: {json.dumps(paths)} }},")
    out.append('};\n')
out.append('/** 1924–39 date stamps by year: each year\'s two date digits (dates.py). Keyed by year, then character. */')
out.append('export const BC_DATES: Readonly<Record<number, Readonly<Record<string, SkeletonGlyph>>>> = {')
for year, glyphs in date_sets:
    out.append(f'  {year}: {{')
    for c, v in glyphs.items():
        out.append(f"    // {dc[year].get(c, 0)} samples\n    {json.dumps(c)}: {{ advance: {v['advance']}, fill: true, paths: [{json.dumps(v['d'])}] }},")
    out.append('  },')
out.append('};\n')
open(sys.argv[1], 'w').write('\n'.join(out))
