/**
 * Source-led research glyphs layered over the production dies, per B.C. format.
 *
 * The registry (generated by scripts/trace-bc-dies/build_research_registry.py)
 * binds each format and production die, or proxy typeface, to research units
 * ordered best first. While a plate renders inside `withResearchContext`, a die
 * takes each character from the first unit that observed it and keeps its
 * production glyph for everything else, so every serial still renders. These
 * are unvalidated research candidates, switchable off with
 * `setResearchDiesEnabled(false)`.
 */
import type { DieProfile } from './engine';
import type { SkeletonGlyph } from './skeleton';

export interface ResearchRegistry {
  /** `[advance, ...paths]` filled outlines at cap height 100. */
  glyphs: (number | string)[][];
  units: Record<string, { role: string; title: string; reviewReady: boolean; glyphs: Record<string, number> }>;
  /** formatId → production die id or `font:<family>` → unit ids, best first. */
  bindings: Record<string, Record<string, string[]>>;
}

const STORAGE_KEY = 'plateforge:research-dies';
let registry: ResearchRegistry | null = null;
let enabled = readEnabled();
let version = 0;
let context: string | null = null;
const listeners = new Set<() => void>();
const merged = new Map<string, DieProfile>();
/** Merged profile → the production profile it was built from. */
const bases = new WeakMap<DieProfile, DieProfile>();

const storage = (): Storage | undefined => (typeof window === 'undefined' ? undefined : window.localStorage);
function readEnabled(): boolean {
  try { return storage()?.getItem(STORAGE_KEY) !== 'off'; } catch { return true; }
}
function changed(): void {
  merged.clear();
  version++;
  for (const l of listeners) l();
}

export function installResearchRegistry(data: ResearchRegistry | null): void { registry = data; changed(); }
export const researchRegistryLoaded = (): boolean => registry !== null;

let loading: Promise<void> | null = null;
/** Fetches the registry once (a separate ~5 MB asset, kept out of the main bundle). */
export function loadResearchDies(): Promise<void> {
  loading ??= import('./research-registry.json?url')
    .then(({ default: url }) => fetch(url))
    .then((r) => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json() as Promise<ResearchRegistry>; })
    .then(installResearchRegistry)
    .catch((e) => { loading = null; console.warn('Research dies unavailable; using production dies.', e); });
  return loading;
}

export const researchDiesEnabled = (): boolean => enabled;
export function setResearchDiesEnabled(on: boolean): void {
  if (on === enabled) return;
  enabled = on;
  try { storage()?.setItem(STORAGE_KEY, on ? 'on' : 'off'); } catch { /* storage blocked */ }
  changed();
}
export function subscribeResearchDies(listener: () => void): () => void {
  listeners.add(listener);
  return () => { listeners.delete(listener); };
}
/** Changes whenever the registry loads or the toggle flips. */
export const researchDiesVersion = (): number => version;

/** Renders `build` with research glyphs for `formatId` (synchronous scene builders only). */
export function withResearchContext<T>(formatId: unknown, build: () => T): T {
  const previous = context;
  context = typeof formatId === 'string' ? formatId : null;
  try { return build(); } finally { context = previous; }
}

/** Which kind of lettering a role names; research units only stand in for the same kind first. */
export function roleClass(role: string): 'serial' | 'legend' | 'date' | 'decal' {
  const r = role.toLowerCase();
  if (r.startsWith('decal') || r.includes('renewal')) return 'decal';
  if (r.includes('serial') || r.startsWith('stack') || r === 'trailer' || r === 'floater') return 'serial';
  if (/year|date|month|day|expiry|century|base/.test(r)) return 'date';
  return 'legend';
}

function activeUnits(key: string): string[] | null {
  if (!enabled || !registry || !context) return null;
  return registry.bindings[context]?.[key] ?? null;
}

/** Units for a role: only that kind of lettering when the format has any, else all, keeping the ranking. */
function unitsFor(units: readonly string[], role?: string): readonly string[] {
  if (!role) return units;
  const same = units.filter((id) => roleClass(registry!.units[id].role) === roleClass(role));
  return same.length ? same : units;
}

function researchGlyphs(units: readonly string[]): Record<string, SkeletonGlyph> {
  const reg = registry!;
  const glyphs: Record<string, SkeletonGlyph> = {};
  for (const id of units) {
    for (const [char, index] of Object.entries(reg.units[id].glyphs)) {
      if (glyphs[char]) continue;
      const [advance, ...paths] = reg.glyphs[index];
      glyphs[char] = { advance: advance as number, paths: paths as string[], fill: true };
    }
  }
  return glyphs;
}

/**
 * The research variant of a production die for the current format, or the die
 * itself when research is off, unloaded, outside a plate, or not bound here.
 * With `text`, a single unit that observed the whole run is preferred, so a
 * word is not assembled from different sources when it need not be.
 */
export function researchVariant(profile: DieProfile, role?: string, text?: string): DieProfile {
  const base = bases.get(profile) ?? profile;
  const units = activeUnits(base.id);
  if (!units?.length) return profile;
  const ranked = unitsFor(units, role);
  const chars = text ? [...new Set(text)].filter((c) => c !== ' ') : [];
  const whole = chars.length ? ranked.find((u) => chars.every((c) => c in registry!.units[u].glyphs)) : undefined;
  const chosen = whole ? [whole] : ranked;
  const key = `${context}|${base.id}|${whole ?? (role ? roleClass(role) : '')}`;
  let p = merged.get(key);
  if (!p) {
    const glyphs = researchGlyphs(chosen);
    const titles = [...new Set(chosen.map((id) => registry!.units[id].title))];
    p = {
      ...base,
      overrides: { ...base.overrides, ...glyphs },
      researchChars: new Set(Object.keys(glyphs)),
      // Filled photo outlines already carry their source slant; only production fallbacks are skewed.
      slant: undefined, fallbackSlant: base.slant,
      evidence: { ...base.evidence, status: 'research-candidate',
        notes: `Research glyphs (${Object.keys(glyphs).sort().join('')}) from ${titles.slice(0, 3).join('; ')}${titles.length > 3 ? ` and ${titles.length - 3} more` : ''}; other characters use the production die. Unvalidated candidates. ${base.evidence.notes}` },
    };
    bases.set(p, base);
    merged.set(key, p);
  }
  return p;
}

const SPACE: SkeletonGlyph = { advance: 28, paths: [], fill: true };
/**
 * A die standing in for a proxy typeface (e.g. Georgia on municipal plates),
 * only when one research unit observed every character of `text`, so a word is
 * never assembled from different sources; otherwise null and the typeface stays.
 */
export function researchTypeface(fontFamily: string, text: string, role: string): DieProfile | null {
  const id = `font:${fontFamily}`;
  const units = activeUnits(id);
  if (!units?.length) return null;
  const chars = [...new Set(text)].filter((c) => c !== ' ');
  const unit = unitsFor(units, role).find((u) => chars.every((c) => c in registry!.units[u].glyphs));
  if (!unit) return null;
  const key = `${context}|${id}|${unit}`;
  let p = merged.get(key);
  if (!p) {
    const glyphs = researchGlyphs([unit]);
    p = {
      id, label: `Research lettering for ${fontFamily}`,
      params: { width: 60, stroke: 12, curve: 'stadium', tracking: 6, one: 'plain', three: 'round', four: 'closed', seven: 'straight', narrow: 0.5, wide: 1.2 },
      overrides: { ' ': SPACE, ...glyphs }, allowConstructedFallback: false, researchChars: new Set(Object.keys(glyphs)),
      evidence: { status: 'research-candidate', specimens: [], notes: `Observed outlines from ${registry!.units[unit].title} replacing a proxy typeface; unvalidated.` },
    };
    merged.set(key, p);
  }
  return p;
}
