#!/usr/bin/env python3
"""Regenerate src/templates/westasia-arabic.ts: Arabic-Indic and Persian digits plus Arabic-script letters as SVG
outlines from two SIL OFL 1.1 fonts (npm packages `parastoo-font` 2.0.1 and `sahel-font` 3.4.0, Saber Rastikerdar).

    npm pack parastoo-font@2.0.1 sahel-font@3.4.0   # then untar; the files used are dist/Parastoo-Bold.ttf and dist/Sahel-Bold.ttf
    python -m pip install fonttools==4.59.1
    python scripts/build-westasia-arabic.py Parastoo-Bold.ttf Sahel-Bold.ttf

No font file is committed or embedded in plates: only path outlines, which OFL permits (see docs/iraq-iran-typography.md).
Glyphs share the 80-unit-tall cell used by westasia-glyphs.ts. Each outline is positioned inside a margin of STROKE/2 so the
renderer can add a stroke of STROKE units (the fonts are lighter than plate dies; see the typography review).
"""
import hashlib, sys
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

STROKE = 3.0                    # units of the 80-tall cell; about 2% of glyph height added on each side
BOX = 80 - STROKE               # outline height once the stroke is added back
BASELINE = 80 - STROKE / 2      # digits and ا sit on this line
CENTRE = 40                     # other letters are centred on this line
DIGITS = '٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹'
LETTERS = 'ابپتثجدرزسشصطعفقکلمنو'   # ه keeps the hand-drawn plate form; ی is taken from the font below
SAHEL = 'ع'                       # best per-glyph overlap of the tested OFL fonts (0.67 v 0.64 for Parastoo)
BASELINE_LETTERS = 'ا'


def outline(font, ch):
    glyphs = font.getGlyphSet(); name = font.getBestCmap()[ord(ch)]
    bounds = BoundsPen(glyphs); glyphs[name].draw(bounds)
    if bounds.bounds is None:
        raise SystemExit(f'blank glyph {ch!r}')
    return glyphs, name, bounds.bounds


def emit(font, ch, scale, mode):
    glyphs, name, (x0, y0, x1, y1) = outline(font, ch)
    s = scale
    if mode == 'fit':                       # digits fitted to the box, as in the typography review
        s = BOX / (y1 - y0)
    elif (y1 - y0) * s > BOX:               # a tall letter shrinks rather than overflowing the cell
        s = BOX / (y1 - y0)
    # Cell y = origin - font_y * s. 'baseline' keeps the font's own baseline; the others place the outline's top edge.
    if mode == 'baseline':
        origin = BASELINE
    else:
        top = STROKE / 2 if mode == 'fit' else CENTRE - (y1 - y0) * s / 2
        origin = top + y1 * s
    transform = (s, 0, 0, -s, STROKE / 2 - x0 * s, origin)
    pen = SVGPathPen(glyphs, ntos=lambda v: f'{v:.1f}'.rstrip('0').rstrip('.'))
    glyphs[name].draw(TransformPen(pen, transform))
    return round((x1 - x0) * s + STROKE, 1), pen.getCommands()


def main(parastoo_path, sahel_path):
    data = {p: Path(p).read_bytes() for p in (parastoo_path, sahel_path)}
    para, sahel = TTFont(parastoo_path), TTFont(sahel_path)
    # One scale for the whole font, from the Persian digits' own heights, so letters keep their weight relative to digits.
    heights = [outline(para, c)[2][3] - outline(para, c)[2][1] for c in '۱۲۳۴۵۷۹']
    k = BOX / (sorted(heights)[len(heights) // 2])
    rows = []
    for ch in DIGITS:
        if ch == '٠':   # the font's Arabic-Indic zero is a diamond; the Wikipedia Iraq plates show a round, oval dot
            rx, ry, cy = 11.0, 13.0, 50.0
            cx = STROKE / 2 + rx
            rows.append((ch, round(2 * rx + STROKE, 1), f'M{cx - rx:g} {cy:g}A{rx:g} {ry:g} 0 1 0 {cx + rx:g} {cy:g}A{rx:g} {ry:g} 0 1 0 {cx - rx:g} {cy:g}Z'))
            continue
        w, d = emit(para, ch, k, 'baseline' if ch in '٠۰' else 'fit')
        rows.append((ch, w, d))
    for ch in LETTERS + 'ی':
        font = sahel if ch in SAHEL else para
        w, d = emit(font, ch, k, 'baseline' if ch in BASELINE_LETTERS else 'centre')
        rows.append((ch, w, d))
    shas = ', '.join(f'{Path(p).name} sha256 {hashlib.sha256(b).hexdigest()[:16]}…' for p, b in data.items())
    out = Path('src/templates/westasia-arabic.ts')
    lines = [
        '/**',
        ' * Arabic-Indic and Persian digits and Arabic-script letters as SVG outlines in the shared 80-unit glyph cell.',
        ' * Generated by scripts/build-westasia-arabic.py from Parastoo Bold and Sahel Bold (Saber Rastikerdar, SIL OFL 1.1;',
        f' * {shas}). Only outlines are stored; no font file ships.',
        ' * Sahel supplies ع and Parastoo everything else; the renderer adds a stroke of NASKH_STROKE units because the fonts are',
        ' * lighter than plate dies. Measured against photographed Iranian plates (docs/iraq-iran-typography.md): ~0.74 flat / 0.71',
        ' * embossed silhouette overlap for the digits tested against 0.47 / 0.46 for the geometric first pass. Not an official die.',
        ' * Each entry is [painted width, path]; the path starts at x = 0.',
        ' */',
        f'export const NASKH_STROKE = {STROKE};',
        'export const NASKH_PLATE_GLYPHS: Record<string, readonly [number, string]> = {',
    ]
    for ch, w, d in rows:
        lines.append(f"  '{ch}': [{w}, '{d}'],")
    lines.append('};')
    out.write_text('\n'.join(lines) + '\n')
    print(f'wrote {out}: {len(rows)} glyphs, {out.stat().st_size} bytes')


if __name__ == '__main__':
    main(*sys.argv[1:3])
