import asyncio,json,os
from pathlib import Path
from playwright.async_api import async_playwright
ROOT=Path(__file__).resolve().parents[1];j=json.loads((ROOT/'public/bc-font-comparisons/die-grouping/catalogue.json').read_text());t=j['timeline']
async def run():
 expected_count=len(j['records']);assert t['coveredPresets']==expected_count and all(x['letteringComponents']for x in j['records']);assert all(x['componentExtractionError'] is None for x in j['records']);assert t['start']==1901 and t['end']==2026
 assert all('productionDateInferred'in r and not r['productionDateInferred']for r in j['records'])
 assert all(i in {r['id']for r in j['records']} for w in t['sourceEvidence']['windows'] for i in w.get('recordIds',[]))
 trailer=next(x for x in j['records']if x['id']=='trailer-1936');assert any(c['die']=='bc-trailer-early-prefix'and c['category']=='prefix'for c in trailer['letteringComponents']);strip=next(x for x in j['records']if x['id']=='1951');assert any(c['die']=='bc-strip-1951'and c['category']=='renewal'for c in strip['letteringComponents'])
 url=os.getenv('DIE_TIMELINE_URL','http://127.0.0.1:8787/bc-font-comparisons/die-grouping/?view=timeline');report={'url':url,'presets':expected_count,'components':t['componentCount'],'bounds':[t['start'],t['end']],'sourceContexts':len(t['sourceEvidence']['windows']),'filters':[],'errors':[]}
 async with async_playwright()as p:
  b=await p.chromium.launch(executable_path=os.getenv('CHROMIUM_EXECUTABLE','/usr/bin/chromium'),args=['--no-sandbox']);page=await b.new_page(viewport={'width':1380,'height':1000});page.on('pageerror',lambda e:report['errors'].append(str(e)));await page.goto(url);await page.wait_for_selector('#timeline-model-chart .gantt-bar');assert await page.locator('#timeline-view').is_visible();assert(await page.locator('#timeline-count').inner_text()).startswith(str(expected_count)+' presets');report['overviewLanes']=await page.locator('#timeline-model-chart .gantt-row').count()-1
  assert await page.locator('#timeline-model-chart .gantt-bar.option').count()>0;option_count=await page.locator('#timeline-model-chart .gantt-bar.option').count();await page.locator('#timeline-options').uncheck();assert await page.locator('#timeline-model-chart .gantt-bar.option').count()==0;await page.locator('#timeline-options').check();assert await page.locator('#timeline-model-chart .gantt-bar.option').count()==option_count;report['selectableAlternatives']=t['selectableAlternativeCount'];report['optionToggleVerified']=True
  await page.locator('#timeline-type').select_option('passenger');await page.locator('#timeline-component').select_option('serial');await page.locator('#timeline-model-chart .gantt-bar.option[title*=\"male/female\"]').first.click();assert 'captured default reproduction' in await page.locator('#timeline-selected-preset').inner_text();report['optionPreviewQualificationVerified']=True;await page.locator('#timeline-type').select_option('');await page.locator('#timeline-component').select_option('')

  width0=await page.locator('#timeline-model-chart .gantt-track').first.evaluate('n=>n.getBoundingClientRect().width');await page.locator('#timeline-zoom').select_option('24');width1=await page.locator('#timeline-model-chart .gantt-track').first.evaluate('n=>n.getBoundingClientRect().width');assert width1==width0*4;report['zoomWidthRatio']=4;await page.locator('#timeline-reset').click()
  for typ in j['coverage']['byType']:
   await page.locator('#timeline-type').select_option(typ);assert await page.locator('#timeline-model-chart .gantt-bar').count()>0;report['filters'].append(typ)
  await page.locator('#timeline-type').select_option('');report['componentCategories']=[]
  for cat in t['categoryLabels']:
   await page.locator('#timeline-component').select_option(cat);assert await page.locator('#timeline-model-chart .gantt-bar').count()>0;report['componentCategories'].append(cat)
  await page.locator('#timeline-type').select_option('trailer');await page.locator('#timeline-component').select_option('prefix');await page.locator('#timeline-layer').select_option('model');await page.locator('#timeline-model-chart .gantt-bar').first.click();await page.locator('#timeline-preset-select').select_option('trailer-1936');assert 'separate T/TR stamp' in await page.locator('#timeline-selected-preset').inner_text();assert 'drawing cap' in await page.locator('#timeline-selected-preset').inner_text();href=await page.locator('#timeline-selected-preset a').filter(has_text='Select in PlateForge').get_attribute('href');assert href=='../../#/ca-bc/trailer-1936';report['prefixSelection']='trailer-1936'
  await page.locator('#timeline-type').select_option('passenger');await page.locator('#timeline-component').select_option('serial');await page.locator('#timeline-layer').select_option('source');await page.locator('#timeline-source-chart .gantt-bar[title*="Waldale · principal"]').click();assert '999-HFK' in await page.locator('#timeline-selection').inner_text();assert 'not factory withdrawal' in await page.locator('#timeline-selection').inner_text();report['waldaleEvidenceSelected']=True
  await page.locator('#timeline-type').select_option('specialty');assert 'Calendar date unassigned' in await page.locator('#timeline-events').inner_text();assert 'mid-B54' in await page.locator('#timeline-events').inner_text();report['undatedSerialTransitionPreserved']=True
  await page.locator('#timeline-type').select_option('municipal');await page.locator('#timeline-component').select_option('serial');await page.locator('#timeline-layer').select_option('source');await page.locator('#timeline-source-chart .gantt-bar[title*="taxi specimens"]').click();assert await page.locator('#timeline-preset-select option').count()==2;await page.locator('#timeline-preset-select').select_option('municipal-vancouver-taxi-1996');assert 'embossed serial' in await page.locator('#timeline-selected-preset').inner_text();report['municipal1996And1997SourceSelectionVerified']=True
  await page.locator('#timeline-type').select_option('official');await page.locator('#timeline-component').select_option('artwork');await page.locator('#timeline-layer').select_option('source');await page.locator('#timeline-source-chart .gantt-bar[title*=\"2016 photograph\"]').click();assert 'after the crest' in await page.locator('#timeline-selection').inner_text();assert await page.locator('#timeline-preset-select option').count()==1;assert await page.locator('#timeline-preset-select').input_value()=='official-lt-governor-arms';assert 'coexist' in await page.locator('#timeline-events').inner_text();report['lieutenantGovernorOverlapQualified']=True
  await page.locator('#timeline-type').select_option('');await page.locator('#timeline-component').select_option('');await page.locator('#timeline-layer').select_option('both');await page.locator('#timeline-start').fill('1920');await page.locator('#timeline-start').dispatch_event('change');await page.locator('#timeline-end').fill('1940');await page.locator('#timeline-end').dispatch_event('change');assert '1920–1940' in await page.locator('#timeline-count').inner_text();report['rangeFilterVerified']=[1920,1940];await page.locator('#timeline-reset').click();assert '1901–2026'in await page.locator('#timeline-count').inner_text()
  await page.locator('#timeline-search').fill('Harrington');assert await page.locator('#timeline-model-chart .gantt-bar').count()>0;assert 'Harrington' in await page.locator('#timeline-model-chart').inner_text();report['fontSearchVerified']='Harrington';await page.locator('#timeline-search').fill('')
  await page.set_viewport_size({'width':390,'height':844});assert await page.evaluate('document.documentElement.scrollWidth<=innerWidth+1');chart=page.locator('#timeline-model-chart');assert await chart.evaluate('n=>n.scrollWidth>n.clientWidth');await chart.evaluate('n=>n.scrollLeft=250');assert await chart.evaluate('n=>n.scrollLeft')>0;assert await page.evaluate('document.documentElement.scrollWidth<=innerWidth+1');report['mobileNoPageOverflow']=True;report['mobileHorizontalPan']=True;await page.screenshot(path='/tmp/bc-timeline-mobile.png');await page.set_viewport_size({'width':1380,'height':1000});await page.screenshot(path='/tmp/bc-timeline-overview.png');assert not report['errors'];await b.close()
 (ROOT/'docs/research/bc-die-grouping/timeline-browser-verification.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))
asyncio.run(run())
